const Joi = require('joi');

module.exports = {
  postValidation: Joi.object({
    categories: Joi.array().min(1),
    isDeliveryRequest: Joi.boolean(),
    from: Joi.string().trim().required(),
    to: Joi.string().trim().required(),
    description: Joi.string().trim().min(20).required(),
    weight: Joi.number(),
    weightFrom: Joi.number(),
    weightTo: Joi.number(),
    length: Joi.number().required(),
    breadth: Joi.number().required(),
    height: Joi.number().required(),
    urgent: Joi.string(),
    deliveryDate: Joi.date().greater('now').required(),
    amountFrom: Joi.number().required(),
    amountTo: Joi.number().required(),
    negotiate: Joi.boolean(),
  }),
  postUpdateValidation: Joi.object({
    categories: Joi.array().min(1),
    isDeliveryRequest: Joi.boolean(),
    from: Joi.string().trim(),
    to: Joi.string().trim(),
    description: Joi.string().trim().min(20),
    weight: Joi.number(),
    weightFrom: Joi.number(),
    weightTo: Joi.number(),
    length: Joi.number(),
    breadth: Joi.number(),
    height: Joi.number(),
    urgent: Joi.string().trim(),
    deliveryDate: Joi.date().greater('now'),
    amountFrom: Joi.number(),
    amountTo: Joi.number(),
    negotiate: Joi.boolean(),
  }),
};
